"""autogenerated by genpy from RCcontroller/channel_values.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class channel_values(genpy.Message):
  _md5sum = "ca7acf8e5a00666a779bed08a3dab8d4"
  _type = "RCcontroller/channel_values"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 channel_1
int32 channel_2
int32 channel_3
int32 channel_4
int32 channel_5
int32 channel_6
int32 channel_7

"""
  __slots__ = ['channel_1','channel_2','channel_3','channel_4','channel_5','channel_6','channel_7']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       channel_1,channel_2,channel_3,channel_4,channel_5,channel_6,channel_7

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(channel_values, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.channel_1 is None:
        self.channel_1 = 0
      if self.channel_2 is None:
        self.channel_2 = 0
      if self.channel_3 is None:
        self.channel_3 = 0
      if self.channel_4 is None:
        self.channel_4 = 0
      if self.channel_5 is None:
        self.channel_5 = 0
      if self.channel_6 is None:
        self.channel_6 = 0
      if self.channel_7 is None:
        self.channel_7 = 0
    else:
      self.channel_1 = 0
      self.channel_2 = 0
      self.channel_3 = 0
      self.channel_4 = 0
      self.channel_5 = 0
      self.channel_6 = 0
      self.channel_7 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.channel_1, _x.channel_2, _x.channel_3, _x.channel_4, _x.channel_5, _x.channel_6, _x.channel_7))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.channel_1, _x.channel_2, _x.channel_3, _x.channel_4, _x.channel_5, _x.channel_6, _x.channel_7,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.channel_1, _x.channel_2, _x.channel_3, _x.channel_4, _x.channel_5, _x.channel_6, _x.channel_7))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.channel_1, _x.channel_2, _x.channel_3, _x.channel_4, _x.channel_5, _x.channel_6, _x.channel_7,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7i = struct.Struct("<7i")
